import http from 'node:http';import fs from 'node:fs/promises';import path from 'node:path';import crypto from 'node:crypto';import {pages,pageByPath} from './source/content.mjs';import {render} from './source/site.mjs';
const PORT=Number(process.env.PORT||8080),DATA=path.resolve(process.env.KEDDEH_DATA_DIR||'data');await fs.mkdir(DATA,{recursive:true});
const interestFile=path.join(DATA,'interest.ndjson'),overrideFile=path.join(DATA,'content-overrides.json');
async function overrides(){try{return JSON.parse(await fs.readFile(overrideFile,'utf8'))}catch{return {}}}
const send=(res,code,obj,headers={})=>{const raw=typeof obj==='string'?obj:JSON.stringify(obj);res.writeHead(code,{'content-type':typeof obj==='string'?'text/html; charset=utf-8':'application/json; charset=utf-8','cache-control':'no-store',...headers});res.end(raw)};
const body=async req=>{const chunks=[];for await(const c of req)chunks.push(c);const raw=Buffer.concat(chunks);if(raw.length>65536)throw Error('BODY_TOO_LARGE');return JSON.parse(raw.toString('utf8')||'{}')};
const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,'http://local');
if(req.method==='GET'&&u.pathname==='/api/health')return send(res,200,{ok:true,schema:'keddeh.frontage.runtime.v1',routes:pages.length,build:process.env.KEDDEH_BUILD_SHA||'local',interestStore:'durable-file',adminOverlay:true});
if(req.method==='POST'&&u.pathname==='/api/interest'){const d=await body(req);const email=String(d.email||'').trim().toLowerCase(),topic=String(d.topic||'').trim(),consent=String(d.consent||'');if(!/^\S+@\S+\.\S+$/.test(email)||!topic||consent!=='learning-v1')return send(res,400,{error:'Enter a valid email, topic and explicit learning consent.'});let rows=[];try{rows=(await fs.readFile(interestFile,'utf8')).trim().split('\n').filter(Boolean).map(JSON.parse)}catch{}if(rows.some(r=>r.email===email))return send(res,200,{ok:true,duplicate:true});const record={id:crypto.randomUUID(),email,topic,consentVersion:'learning-v1',registeredAt:new Date().toISOString()};await fs.appendFile(interestFile,JSON.stringify(record)+'\n');return send(res,201,{ok:true,duplicate:false,id:record.id})}
if(req.method==='PATCH'&&u.pathname==='/api/admin/content'){const token=(req.headers.authorization||'').replace(/^Bearer\s+/,'');const expected=process.env.KEDDEH_ADMIN_TOKEN||'';const authorised=expected&&token.length===expected.length&&crypto.timingSafeEqual(Buffer.from(token),Buffer.from(expected));if(!authorised)return send(res,401,{error:'UNAUTHORISED'});const d=await body(req);if(!pageByPath.has(d.path)||typeof d.patch!=='object')return send(res,400,{error:'INVALID_CONTENT_PATCH'});const all=await overrides();all[d.path]={...(all[d.path]||{}),...d.patch,updatedAt:new Date().toISOString()};const tmp=overrideFile+'.tmp';await fs.writeFile(tmp,JSON.stringify(all,null,2));await fs.rename(tmp,overrideFile);return send(res,200,{ok:true,path:d.path,updatedAt:all[d.path].updatedAt})}
if(req.method==='GET'){const p=u.pathname==='/'?'/':u.pathname.replace(/\/$/,'')||'/';const base=pageByPath.get(u.pathname)||pageByPath.get(p)||pageByPath.get(p+'/');if(base){const ov=(await overrides())[base.path];const merged=ov?{...base,...ov,sections:ov.sections||base.sections,primaryAction:ov.primaryAction||base.primaryAction}:base;return send(res,200,render(base.path,merged),{'content-security-policy':"default-src 'self'; style-src 'unsafe-inline'; script-src 'unsafe-inline'; img-src 'self' data:; connect-src 'self'"})}}
return send(res,404,{error:'NOT_FOUND',recovery:'/'})}catch(e){return send(res,500,{error:'RUNTIME_ERROR',detail:e.message})}});
server.listen(PORT,'0.0.0.0',()=>console.log(JSON.stringify({event:'KEDDEH_FRONTAGE_READY',port:PORT,routes:pages.length})));
